name: CDK Workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      action:
        description: 'CDK Action to perform (deploy/destroy)'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy
      stack:
        description: 'Stack to destroy (required for destroy action)'
        required: false
        type: choice
        options:
          - all
          - AppRunnerStackDev
          - CacheStackDev
          - CloudFrontStackDev
          - DatabaseStackDev
          - EcrStackDev
          - VpcStackDev

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  cdk-action:
    name: CDK Action
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment: development
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActionsCDK

      - name: CDK Bootstrap
        if: github.event.inputs.action != 'destroy'
        run: cdk bootstrap

      - name: CDK Synth
        run: cdk synth --context environment=dev --context branch=develop

      - name: CDK Deploy
        if: github.event.inputs.action != 'destroy'
        run: cdk deploy --all --require-approval never --context environment=dev --context branch=develop

      - name: Destroy All Stacks
        if: github.event.inputs.action == 'destroy' && github.event.inputs.stack == 'all'
        run: |
          echo "⚠️ WARNING: This will destroy all CDK managed resources!"
          echo "Proceeding with destruction in 10 seconds..."
          sleep 10
          echo "Destroying CloudFront Stack..."
          cdk destroy CloudFrontStackDev --force --context environment=dev --context branch=develop || true
          echo "Destroying AppRunner Stack..."
          cdk destroy AppRunnerStackDev --force --context environment=dev --context branch=develop || true
          echo "Destroying Cache Stack..."
          cdk destroy CacheStackDev --force --context environment=dev --context branch=develop || true
          echo "Destroying Database Stack..."
          cdk destroy DatabaseStackDev --force --context environment=dev --context branch=develop || true
          echo "Destroying ECR Stack..."
          cdk destroy EcrStackDev --force --context environment=dev --context branch=develop || true
          echo "Destroying VPC Stack..."
          cdk destroy VpcStackDev --force --context environment=dev --context branch=develop || true

      - name: Destroy AppRunner Stack
        if: github.event.inputs.action == 'destroy' && github.event.inputs.stack == 'AppRunnerStackDev'
        run: |
          echo "⚠️ WARNING: Destroying AppRunner Stack"
          echo "Proceeding with destruction in 5 seconds..."
          sleep 5
          cdk destroy AppRunnerStackDev --force --context environment=dev --context branch=develop

      - name: Destroy Cache Stack
        if: github.event.inputs.action == 'destroy' && github.event.inputs.stack == 'CacheStackDev'
        run: |
          echo "⚠️ WARNING: Destroying Cache Stack"
          echo "Proceeding with destruction in 5 seconds..."
          sleep 5
          cdk destroy CacheStackDev --force --context environment=dev --context branch=develop

      - name: Destroy Database Stack
        if: github.event.inputs.action == 'destroy' && github.event.inputs.stack == 'DatabaseStackDev'
        run: |
          echo "⚠️ WARNING: Destroying Database Stack"
          echo "Proceeding with destruction in 5 seconds..."
          sleep 5
          cdk destroy DatabaseStackDev --force --context environment=dev --context branch=develop

      - name: Destroy ECR Stack
        if: github.event.inputs.action == 'destroy' && github.event.inputs.stack == 'EcrStackDev'
        run: |
          echo "⚠️ WARNING: Destroying ECR Stack"
          echo "Proceeding with destruction in 5 seconds..."
          sleep 5
          cdk destroy EcrStackDev --force --context environment=dev --context branch=develop

      - name: Destroy CloudFront Stack
        if: github.event.inputs.action == 'destroy' && github.event.inputs.stack == 'CloudFrontStackDev'
        run: |
          echo "⚠️ WARNING: Destroying CloudFront Stack"
          echo "Proceeding with destruction in 5 seconds..."
          sleep 5
          cdk destroy CloudFrontStackDev --force --context environment=dev --context branch=develop

      - name: Destroy VPC Stack
        if: github.event.inputs.action == 'destroy' && github.event.inputs.stack == 'VpcStackDev'
        run: |
          echo "⚠️ WARNING: Destroying VPC Stack"
          echo "Proceeding with destruction in 5 seconds..."
          sleep 5
          cdk destroy VpcStackDev --force --context environment=dev --context branch=develop